version: '3'
services:
  backend:
    image: motion_backend:latest
    ports:
    - 8000:8000
    volumes:
    - ./backend:/backend
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_db: