version: '3'
services:
  backend:
    image: registry.gitlab.propulsion-home.ch/habib-kadiri/week-7/docker_motion:latest
    ports:
    - 8000:8000
    volumes:
    - ./backend:/backend

    depends_on:
      - db
    command: 'gunicorn --reload -w 4 -b 0.0.0.0:8000 project.wsgi:application'

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d


volumes:
  postgres_db:
