version: '3'
services:
  backend:
    image: registry.gitlab.propulsion-home.ch/habib-kadiri/week-7/docker_motion:latest
    volumes:
    - static-files:/static
    - frontend:/frontend/build
    - media-files:/backend/media
    env_file:
      - ./env/prod.env
    command: 'sh /scripts/run.sh'
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/prod.env
    volumes:
      - postgres_db:/var/lib/postgresql/data


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static
      - media-files:/media
      - frontend:/frontend
      - /etc/letsencrypt/:/etc/letsencrypt/


volumes:
  postgres_db:
  static-files:
  media-files:
  frontend:


