# Generated by Django 3.0.3 on 2020-06-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='used',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
