# Generated by Django 3.0.3 on 2020-07-02 17:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200702_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='things_user_likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
