# Generated by Django 3.0.3 on 2020-06-22 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendrequests', '0003_auto_20200622_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('receiver', 'requester')},
        ),
    ]
