# Generated by Django 3.0.3 on 2020-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendrequests', '0004_auto_20200622_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='P', max_length=2),
        ),
    ]
