# Generated by Django 3.0.3 on 2020-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registrationprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='code',
            field=models.CharField(default='393421652733897', help_text='random code used for registration and for password reset', max_length=15),
        ),
    ]
