# Generated by Django 3.0.3 on 2020-06-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
